version: "3.1"
services:
  dev:
   container_name: chat_project
   image: distributed_subject:1
   build: 
    context: .
    dockerfile: Dockerfile
   command: tail -f /dev/null # This keep container alive
   volumes:
    - ubuntu_disk:/code
   ports:
    - "8000:8080"
    - "4567:4567"
   #depends_on:
   # - db
   networks:
    - work_common
networks:
  work_common:
    external: true
volumes:
  ubuntu_disk:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /work/